version: "3.3"

networks:
  esl:

services:
  app:
    build:
      context: ./.docker/nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: esl_app
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - php
      - db
    networks:
      - esl

  php:
    build:
      context: ./.docker/php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: esl_php
    volumes:
      - .:/var/www/html
    networks:
      - esl

  db:
    image: mariadb:10.6
    container_name: esl_db
    restart: unless-stopped
    tty: true
    volumes:
      - esl_db:/var/lib/mysql
    ports:
      - "33069:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - esl

  redis:
    image: redis:latest
    container_name: esl_redis
    ports:
      - "6382:6379"
    networks:
      - esl

volumes:
  esl_db:



