services:
  attribute.query.getAttributesHandler:
    class: Arcmedia\Esl\Attribute\Application\Query\GetAttributesHandler
    arguments:
      - '@attribute.repository.doctrineAttributeRepository'

  attribute.command.saveAttributesHandler:
    class: Arcmedia\Esl\Attribute\Application\Command\SaveAttributesHandler
    arguments:
      - '@attribute.repository.doctrineAttributeRepository'
      - '@attribute.services.uuidGenerator'
