category:
    resource: ../src/Esl/Category/Infrastructure/Routes/routes.yaml

attribute:
  resource: ../src/Esl/Attribute/Infrastructure/Routes/routes.yaml

attributeSet:
  resource: ../src/Esl/AttributeSet/Infrastructure/Routes/routes.yaml

product:
  resource: ../src/Esl/Product/Infrastructure/Routes/routes.yaml