services:
  esl.controller.categories.getCategories:
    class: Arcmedia\Esl\Category\Infrastructure\Ui\Http\Controller\GetCategoryController
    arguments:
      - '@category.query.category.getCategoriesHandler'
    public: true

  esl.controller.categories.saveCategory:
    class: Arcmedia\Esl\Category\Infrastructure\Ui\Http\Controller\SaveCategoryController
    arguments:
      - '@category.command.saveCategoryHandler'
    public: true

  esl.controller.categories.importCategories:
    class: Arcmedia\Esl\Category\Infrastructure\Ui\Http\Controller\ImportCategoriesXlsxFileController
    arguments:
      - '@category.command.saveManyCategoriesHandler'
      - '@redis.redisService'
      - '@category.services.uuidGenerator'
    public: true