services:
  category.query.category.getCategoriesHandler:
    class: Arcmedia\Esl\Category\Application\Query\GetCategoriesHandler
    arguments:
      - '@category.repository.doctrineCategoryRepository'

  category.command.saveCategoryHandler:
    class: Arcmedia\Esl\Category\Application\Command\SaveCategoryHandler
    arguments:
      - '@category.repository.doctrineCategoryRepository'
      - '@category.services.uuidGenerator'

  category.command.saveManyCategoriesHandler:
    class: Arcmedia\Esl\Category\Application\Command\SaveManyCategoriesHandler
    arguments:
      - '@category.repository.doctrineCategoryRepository'
      - '@category.services.uuidGenerator'