services:
  esl.controller.attributeSet.getAttributeSet:
    class: Arcmedia\Esl\AttributeSet\Infrastructure\Ui\Http\Controller\GetAttributeSetController
    arguments:
      - '@attributeSet.query.attributeSet.getAttributesSetHandler'
    public: true

  esl.controller.attributesSet.saveAttributesSet:
    class: Arcmedia\Esl\AttributeSet\Infrastructure\Ui\Http\Controller\SaveAttributeSetController
    arguments:
      - '@attributeSet.query.attributeSet.saveAttributesSetHandler'
    public: true