services:
  attributeSet.query.attributeSet.getAttributesSetHandler:
    class: Arcmedia\Esl\AttributeSet\Application\Query\GetAttributesSetHandler
    arguments:
      - '@attributeSet.repository.doctrineAttributeSetRepository'