services:
  attributeSet.query.attributeSet.getAttributesSetHandler:
    class: Arcmedia\Esl\AttributeSet\Application\Query\GetAttributesSetHandler
    arguments:
      - '@attributeSet.repository.doctrineAttributeSetRepository'

  attributeSet.command.saveAttributeSetHandler:
    class: Arcmedia\Esl\AttributeSet\Application\Command\SaveAttributeSetHandler
    arguments:
      - '@attributeSet.repository.doctrineAttributeSetRepository'
      - '@attribute.services.uuidGenerator'